site_name: BlueOS Developer Documentation
site_url: https://blueos.aloyce.com/
theme:
  name: material
 # custom_dir: overrides
  logo: aloycian (4).png
  palette:
    primary: black
    accent: blue
    scheme: slate
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.sections
    - navigation.expand
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tooltips
    #- navigation.footer

plugins:
  - search
  - blog
  - tags:
      tags_file: tags.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Getting Started: 
      - Installation: index.md
  - Aloyce: 
      # - Licensing: aloyce/licensing.md
      - Aloyce Installation Manager: aloyce/aim.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Aloyce-inc
      name: Aloyce on Github

copyright: Copyright &copy; 2024 - 2025 Aloyce

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/Aloyce-inc

