name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: pip install mkdocs mkdocs-material

      - run: mkdocs build

      - run: echo 'blueos.aloyce.com' > site/CNAME

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: site

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Deploy Pages
        uses: actions/deploy-pages@v3
